import { Injectable, NestMiddleware } from '@nestjs/common';
import { NextFunction, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { RequestWithCorrelation } from '@/types/express.types';
import { CORRELATION_ID_HEADER, REQUEST_ID_HEADER } from '@/config/app.constants';
import { CorrelationService } from '@/modules/common/correlation/correlation.service';

/**
 * Correlation ID Middleware
 *
 * Ensures every request has both a correlation ID and a request ID for tracing and debugging.
 * Runs before guards, interceptors, and exception filters.
 *
 * Correlation ID:
 * - Provided by client via header 'x-correlation-id'
 * - If not provided, generates a new UUID v4
 * - Stored in CLS (AsyncLocalStorage) via CorrelationService
 * - Propagated to all downstream calls
 * - Used to trace a logical operation across multiple requests
 *
 * Request ID:
 * - Always generated by the application for each request (UUID v4)
 * - Different from correlation ID (allows differentiating retries)
 * - Stored in CLS (AsyncLocalStorage) via CorrelationService
 * - Included in internal logs
 *
 * Both IDs are:
 * - Stored in CLS for global access (no need to pass request object)
 * - Added to response headers (x-correlation-id, x-request-id)
 * - Accessible via CorrelationService from anywhere in the app
 *
 * Priority for Correlation ID:
 * 1. Uses 'x-correlation-id' header if provided by client
 * 2. Generates a new UUID v4 as fallback
 *
 * @example
 * // Register in app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer.apply(CorrelationIdMiddleware).forRoutes('*');
 *   }
 * }
 *
 * @example
 * // Access IDs from anywhere (no request object needed)
 * constructor(private readonly correlation: CorrelationService) {}
 *
 * const correlationId = this.correlation.getCorrelationId();
 * const requestId = this.correlation.getRequestId();
 */
@Injectable()
export class CorrelationIdMiddleware implements NestMiddleware {
	constructor(private readonly correlation: CorrelationService) {}

	use(req: RequestWithCorrelation, res: Response, next: NextFunction): void {
		// Extract or generate correlation ID
		const correlationId = this.getOrCreateCorrelationId(req);

		// Always generate a new request ID for this specific request
		const requestId = this.getUniqueId();

		// Store all IDs in CLS (AsyncLocalStorage) for global access
		this.correlation.setCorrelationId(correlationId);
		this.correlation.setRequestId(requestId);

		// Add both IDs to response headers so clients can track their requests
		res.setHeader(CORRELATION_ID_HEADER, correlationId);
		res.setHeader(REQUEST_ID_HEADER, requestId);

		next();
	}

	/**
	 * Generates a unique ID using UUID v4
	 * @returns A unique ID
	 */
	private getUniqueId(): string {
		return uuidv4();
	}

	/**
	 * Gets the correlation ID from request headers or generates a new one
	 * Priority:
	 * 1. x-correlation-id header (from client)
	 * 2. Generate new UUID v4
	 *
	 * @param req - Request object
	 * @returns Correlation ID string
	 */
	private getOrCreateCorrelationId(req: RequestWithCorrelation): string {
		const headerCorrelationId = req.headers[CORRELATION_ID_HEADER];

		if (headerCorrelationId) {
			if (!Array.isArray(headerCorrelationId)) {
				return headerCorrelationId;
			}

			const correlationId = headerCorrelationId[0];

			if (correlationId) {
				return correlationId;
			}
		}

		return this.getUniqueId();
	}
}
